import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
  SchemaType,
} from '@google/generative-ai';
import { PrismaService } from '../prisma/prisma.service';
import {
  GITHUB_SCORE_WEIGHT,
  INTERVIEW_SCORE_WEIGHT,
  getConfidenceWeights,
  MAX_DISCREPANCY_REDUCTION,
  ACCOUNT_AGE_THRESHOLD_DAYS,
  WARNING_TEXTS,
} from './config/scoring.config';
import type { GithubConfidenceTier } from './config/scoring.config';
import type {
  InterviewAnalysis,
  TranscriptEntry,
} from './dto/interview-events.dto';
import type { RepoSignals } from '../github-sync/github-sync.service';

// ─── Constants ────────────────────────────────────────────────────────────────

/** Baseline questions asked every time, in order, one per turn */
const BASELINE_QUESTIONS = [
  // Bio question — first, to populate bio_summary
  'Tell us about yourself — your background, what you\'re into, what kind of work excites you.',
  'What roles do you typically take on in a team? (Backend, Frontend, Mobile, AI/ML, Design/UI, Product/PM, DevOps) — and what is your primary tech stack?',
  'Tell me about a few projects you have worked on recently.',
  'Of those projects, which ones did you actually finish and ship? What happened to the others?',
  'When a project gets difficult or you hit a blocker, what do you typically do?',
  'How do you usually communicate with teammates during a project — how often, and on what channels?',
  'On average, how many hours a day can you realistically commit to a hackathon or short-term project?',
];

/**
 * Expanded question set for low-confidence users (thin/no GitHub data).
 * These compensate for the missing GitHub signal — specificity and consistency
 * across these answers is weighted heavily in the specificity_score.
 */
const LOW_CONFIDENCE_EXPANDED_QUESTIONS = [
  'Walk me through a project you\'re proud of — even one not on GitHub. What did you build, and what was the hardest part?',
  // Note: immediate specific follow-up on whatever they name is handled by Gemini's contextual follow-up logic
  'Tell me about a time you wanted to quit a project. What made you stop, or what made you push through?',
  'If a teammate messaged you at 11pm the night before a deadline saying they\'re stuck, what would you actually do?',
  'What\'s something technical you learned recently that you didn\'t know a year ago?',
  // Note: the light technical-reasoning question scoped to their claimed stack is generated by Gemini contextually
];

/**
 * Additional question for old accounts (>1 year) with thin/no data.
 * Neutrally phrased — asks for context, not accusation.
 */
const OLD_ACCOUNT_QUESTION_TEMPLATE =
  'We checked both your public and private GitHub repositories, and there wasn\'t much activity since {accountCreatedDate} — can you tell us what you\'ve mostly been working on?';

const GEMINI_MODEL = 'gemini-3.6-flash';

/** Safety settings — neutral for professional context */
const SAFETY_SETTINGS = [
  { category: HarmCategory.HARM_CATEGORY_HARASSMENT,        threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,       threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
];

/** JSON schema enforced by Gemini responseSchema (controlled generation) */
const ANALYSIS_RESPONSE_SCHEMA: import('@google/generative-ai').ObjectSchema = {
  type: SchemaType.OBJECT as const,
  properties: {
    specificity_score: {
      type: SchemaType.NUMBER,
      description: 'Overall specificity and concreteness of answers, 0–100',
    },
    declared_hours_per_day: {
      type: SchemaType.NUMBER,
      description: 'Hours per day the user declared they can commit',
    },
    role_tags: {
      type: SchemaType.ARRAY,
      description: 'List of role tags extracted from response from: Backend, Frontend, Mobile, AI/ML, Design/UI, Product/PM, DevOps',
      items: { type: SchemaType.STRING },
    },
    primary_stack: {
      type: SchemaType.STRING,
      description: 'Concise text summary of user\'s primary tech stack, e.g. "Node.js, TypeScript, NestJS"',
    },
    flagged_discrepancies: {
      type: SchemaType.ARRAY,
      items: {
        type: SchemaType.OBJECT,
        properties: {
          repo:             { type: SchemaType.STRING },
          issue:            { type: SchemaType.STRING },
          user_explanation: { type: SchemaType.STRING },
        },
        required: ['repo', 'issue', 'user_explanation'],
      },
    },
    communication_style_notes: {
      type: SchemaType.STRING,
      description: 'Neutral notes on how the user described their communication habits',
    },
    bio_summary: {
      type: SchemaType.STRING,
      description: 'A concise summary of the user\'s self-described background, interests, and what kind of work excites them, based on their response to the bio question',
    },
    discrepancy_explanations: {
      type: SchemaType.ARRAY,
      description: 'For each flagged discrepancy where the user provided an explanation, assess the quality and compute a capped reduction',
      items: {
        type: SchemaType.OBJECT,
        properties: {
          repo:                { type: SchemaType.STRING },
          issue:               { type: SchemaType.STRING },
          original_weight:     { type: SchemaType.NUMBER, description: 'Weight this discrepancy would have had without explanation (0-1)' },
          explanation_quality: { type: SchemaType.NUMBER, description: 'How concrete and verifiable the explanation was (0-1)' },
          reduction_applied:   { type: SchemaType.NUMBER, description: 'Actual reduction applied, capped at MAX_DISCREPANCY_REDUCTION (0-0.5)' },
        },
        required: ['repo', 'issue', 'original_weight', 'explanation_quality', 'reduction_applied'],
      },
    },
  },
  required: [
    'specificity_score',
    'declared_hours_per_day',
    'role_tags',
    'primary_stack',
    'flagged_discrepancies',
    'communication_style_notes',
    'bio_summary',
    'discrepancy_explanations',
  ],
};

/** JSON schema for score explanation summary generation */
const SCORE_EXPLANATION_SCHEMA: import('@google/generative-ai').ObjectSchema = {
  type: SchemaType.OBJECT as const,
  properties: {
    explanation: {
      type: SchemaType.STRING,
      description: 'One short paragraph explaining the score composition in plain terms',
    },
  },
  required: ['explanation'],
};

// ─── Service ──────────────────────────────────────────────────────────────────

@Injectable()
export class InterviewService {
  private readonly logger = new Logger(InterviewService.name);
  private readonly genAI: GoogleGenerativeAI;

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {
    const apiKey = this.config.get<string>('GEMINI_API_KEY');
    if (!apiKey) throw new Error('GEMINI_API_KEY is not set in environment');
    this.genAI = new GoogleGenerativeAI(apiKey);
  }

  // ── Public: start a new interview ─────────────────────────────────────────

  /**
   * Validates preconditions, creates/resets the interview_sessions row,
   * and streams the first baseline question back via the provided callback.
   *
   * Now also branches question sets based on github_confidence tier and
   * returns the pre-interview warning text in the response.
   *
   * @param userId     The user whose interview is starting
   * @param onChunk    Called with each raw text chunk as it streams
   * @param onComplete Called with the full assembled message when streaming ends
   * @returns          The new sessionId and pre-interview warning
   */
  async startInterview(
    userId: string,
    onChunk: (chunk: string, sessionId: string) => void,
    onComplete: (fullText: string, turnIndex: number, sessionId: string, isFinished?: boolean) => void,
  ): Promise<{ sessionId: string; preInterviewWarning: string }> {
    // ── 1. Precondition: github_metrics must exist (complete OR insufficient_data) ──
    const metrics = await this.prisma.githubMetrics.findUnique({
      where: { userId },
    });

    if (!metrics || !['complete', 'insufficient_data'].includes(metrics.status)) {
      throw new Error(
        'GitHub metrics are not yet ready. Cannot start interview.',
      );
    }

    // ── 2. Check if interview is already complete (one-time onboarding interview) ──
    const existingSession = await this.prisma.interviewSession.findUnique({
      where: { userId },
    });

    if (existingSession && existingSession.status === 'complete') {
      throw new Error(
        'Interview has already been completed. Retaking the interview is not allowed.',
      );
    }

    const session = await this.prisma.interviewSession.upsert({
      where: { userId },
      create: {
        userId,
        status: 'in_progress',
        transcriptJson: [],
      },
      update: {
        status: 'in_progress',
        transcriptJson: [],
        structuredOutput: undefined,
        bioSummary: null,
        errorReason: null,
      },
    });

    this.logger.log(`Interview session ${session.id} started for user ${userId}`);

    // ── 3. Build system prompt with GitHub metrics context ────────────────
    const repoBreakdown = (metrics.repoBreakdown ?? []) as unknown as RepoSignals[];
    const githubConfidence = (metrics.githubConfidence ?? 'insufficient') as GithubConfidenceTier;
    const accountCreatedAt = metrics.accountCreatedAt;
    const systemPrompt = this.buildSystemPrompt(repoBreakdown, githubConfidence, accountCreatedAt);

    // ── 4. Stream the first baseline question ─────────────────────────────
    const firstQuestion = BASELINE_QUESTIONS[0];
    await this.streamGeminiTurn(
      session.id,
      userId,
      systemPrompt,
      [],            // empty history — first turn
      firstQuestion, // The AI asks this question to the user (we inject it)
      (chunk) => onChunk(chunk, session.id),
      (fullText, turnIndex, isFinished) => onComplete(fullText, turnIndex, session.id, isFinished),
      0,             // turnIndex
    );

    return {
      sessionId: session.id,
      preInterviewWarning: WARNING_TEXTS.preInterview,
    };
  }

  /**
   * Resumes an existing active interview session if status === 'in_progress'.
   * Sanitizes incomplete turns (if disconnect happened mid-stream before assistant reply).
   * If no active in_progress session exists, returns resumed: false.
   */
  async resumeInterview(userId: string): Promise<{
    resumed: boolean;
    sessionId: string;
    transcript: TranscriptEntry[];
    preInterviewWarning: string;
    isFinished?: boolean;
  }> {
    const session = await this.prisma.interviewSession.findUnique({
      where: { userId },
    });

    if (!session || session.status !== 'in_progress') {
      return {
        resumed: false,
        sessionId: '',
        transcript: [],
        preInterviewWarning: WARNING_TEXTS.preInterview,
      };
    }

    let transcript = (session.transcriptJson as unknown as TranscriptEntry[]) ?? [];

    // Edge case: disconnect happened mid-stream after user answer but before assistant response was persisted
    if (transcript.length > 0 && transcript[transcript.length - 1].role === 'user') {
      this.logger.warn(
        `Session ${session.id} transcript ended with un-replied user answer. Rolling back trailing turn for resume.`,
      );
      transcript = transcript.slice(0, -1);
      await this.prisma.interviewSession.update({
        where: { id: session.id },
        data: { transcriptJson: transcript as any },
      });
    }

    const metrics = await this.prisma.githubMetrics.findUnique({ where: { userId } });
    const githubConfidence = (metrics?.githubConfidence ?? 'insufficient') as GithubConfidenceTier;
    const accountCreatedAt = metrics?.accountCreatedAt ?? null;
    const allQuestions = this.getQuestionSet(githubConfidence, accountCreatedAt);
    const completedAiTurns = transcript.filter((t) => t.role === 'assistant').length;
    const lastAssistantMsg = [...transcript].reverse().find((t) => t.role === 'assistant')?.content || '';

    const isFinished =
      lastAssistantMsg.includes('[INTERVIEW_COMPLETE]') ||
      (completedAiTurns >= allQuestions.length && transcript[transcript.length - 1]?.role === 'assistant');

    this.logger.log(
      `Interview session ${session.id} resumed for user ${userId} (${transcript.length} messages in transcript)`,
    );

    return {
      resumed: true,
      sessionId: session.id,
      transcript,
      preInterviewWarning: WARNING_TEXTS.preInterview,
      isFinished,
    };
  }

  // ── Public: handle a user answer ─────────────────────────────────────────

  /**
   * Appends the user's answer to the transcript, persists immediately,
   * then streams the next AI question/follow-up.
   *
   * Now includes branching logic for low-confidence expanded questions.
   *
   * @returns true if the interview should continue, false if it's complete
   */
  async continueInterview(
    userId: string,
    sessionId: string,
    userAnswer: string,
    onChunk: (chunk: string, sessionId: string) => void,
    onComplete: (fullText: string, turnIndex: number, sessionId: string, isFinished?: boolean) => void,
  ): Promise<boolean> {
    // ── 1. Load current session ───────────────────────────────────────────
    const session = await this.prisma.interviewSession.findUnique({
      where: { id: sessionId },
    });

    if (!session || session.status !== 'in_progress') {
      throw new Error(`Session ${sessionId} is not active`);
    }

    const transcript = (session.transcriptJson as unknown as TranscriptEntry[]) ?? [];

    // ── 2. Determine current turn index (number of completed AI turns so far)
    const completedAiTurns = transcript.filter((t) => t.role === 'assistant').length;
    const nextTurnIndex = completedAiTurns; // 0-based index of the AI's next response

    // ── 3. Append user answer + persist immediately ───────────────────────
    const updatedTranscript: TranscriptEntry[] = [
      ...transcript,
      { role: 'user', content: userAnswer, timestamp: new Date().toISOString() },
    ];

    await this.prisma.interviewSession.update({
      where: { id: sessionId },
      data: { transcriptJson: updatedTranscript as any },
    });

    // ── 4. Determine the full question set based on confidence tier ───────
    const metrics = await this.prisma.githubMetrics.findUnique({ where: { userId } });
    const repoBreakdown = (metrics?.repoBreakdown ?? []) as unknown as RepoSignals[];
    const githubConfidence = (metrics?.githubConfidence ?? 'insufficient') as GithubConfidenceTier;
    const accountCreatedAt = metrics?.accountCreatedAt ?? null;
    const systemPrompt = this.buildSystemPrompt(repoBreakdown, githubConfidence, accountCreatedAt);

    const allQuestions = this.getQuestionSet(githubConfidence, accountCreatedAt);
    const hasMoreQuestions = completedAiTurns < allQuestions.length;

    let fullResponse = '';

    if (hasMoreQuestions) {
      // Inject the next question directly
      const nextQuestion = allQuestions[completedAiTurns];
      fullResponse = nextQuestion;

      // Persist the AI's question to transcript
      const withAiTurn: TranscriptEntry[] = [
        ...updatedTranscript,
        { role: 'assistant', content: fullResponse, timestamp: new Date().toISOString() },
      ];
      await this.prisma.interviewSession.update({
        where: { id: sessionId },
        data: { transcriptJson: withAiTurn as any },
      });

      // Emit as if it streamed (send full text as one chunk, then complete)
      onChunk(fullResponse, sessionId);
      onComplete(fullResponse, nextTurnIndex, sessionId, false);
      return true; // interview continues
    } else {
      // All scripted questions answered — let Gemini generate a follow-up or signal completion
      fullResponse = await this.streamGeminiTurn(
        sessionId,
        userId,
        systemPrompt,
        updatedTranscript,
        null, // no injected question — let Gemini decide
        (chunk) => onChunk(chunk, sessionId),
        (fullText, turnIndex, isFinished) => onComplete(fullText, turnIndex, sessionId, isFinished),
        nextTurnIndex,
      );

      // Check if Gemini signalled completion
      return !fullResponse.includes('[INTERVIEW_COMPLETE]');
    }
  }

  // ── Public: finalise and produce structured output ────────────────────────

  /**
   * Sends the full transcript to Gemini with responseSchema enforcement,
   * validates the output, writes commitment_scores, marks session complete.
   * Now uses confidence-weighted scoring, capped discrepancy adjustments,
   * bio extraction, and score explanation summary generation.
   *
   * Retries once on failure; marks failed on second failure.
   */
  async finaliseInterview(
    userId: string,
    sessionId: string,
    emitComplete: (payload: {
      commitmentScore: number;
      githubScore: number;
      interviewScore: number;
      appliedGithubWeight: number;
      appliedInterviewWeight: number;
      declaredHoursPerDay: number | null;
      flaggedDiscrepancies: Array<{ repo: string; issue: string; userExplanation: string }>;
      communicationStyleNotes: string;
      discrepancyResolutionPattern: number | null;
      scoreExplanationSummary: string | null;
      githubConfidence: GithubConfidenceTier;
      preInterviewWarning: string;
    }) => void,
    emitError: (reason: string) => void,
  ): Promise<void> {
    const session = await this.prisma.interviewSession.findUnique({
      where: { id: sessionId },
    });
    if (!session) return;

    const transcript = (session.transcriptJson as unknown as TranscriptEntry[]) ?? [];

    let analysis: InterviewAnalysis | null = null;
    let lastError = '';

    // ── Retry loop: max 2 attempts ────────────────────────────────────────
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        analysis = await this.runStructuredAnalysis(transcript);
        break; // success
      } catch (err) {
        lastError = (err as Error).message;
        this.logger.warn(`Structured analysis attempt ${attempt} failed: ${lastError}`);
        if (attempt === 2) {
          // Both attempts failed — mark session failed and emit error
          await this.prisma.interviewSession.update({
            where: { id: sessionId },
            data: { status: 'failed', errorReason: lastError },
          });
          emitError(lastError);
          return;
        }
        // Wait 1s before retry
        await new Promise((r) => setTimeout(r, 1000));
      }
    }

    if (!analysis) return;

    // ── Get GitHub confidence and compute dynamic weights ─────────────────
    const metrics = await this.prisma.githubMetrics.findUnique({ where: { userId } });
    const githubConfidence = (metrics?.githubConfidence ?? 'insufficient') as GithubConfidenceTier;
    const githubScore = metrics?.githubConsistencyScore ?? 0;
    const interviewScore = analysis.specificity_score;

    // Dynamic weighting based on confidence tier
    // (See scoring.config.ts for design rationale — this is compensation for
    // sparse GitHub evidence, not a general downgrade of GitHub's importance)
    const { githubWeight, interviewWeight } = getConfidenceWeights(githubConfidence);

    // ── Capped discrepancy adjustments ────────────────────────────────────
    // When a user explains a flagged discrepancy, the explanation can reduce
    // that discrepancy's weight by up to MAX_DISCREPANCY_REDUCTION (50%).
    // Never fully erase it — there's always a residual signal.
    const discrepancyExplanations = analysis.discrepancy_explanations ?? [];
    const cappedAdjustments = discrepancyExplanations.map((de) => ({
      repo: de.repo,
      issue: de.issue,
      originalWeight: de.original_weight,
      reductionApplied: Math.min(de.reduction_applied, MAX_DISCREPANCY_REDUCTION),
      cappedAt: MAX_DISCREPANCY_REDUCTION,
    }));

    // Discrepancy resolution pattern: ratio of discrepancies flagged vs explained.
    // Someone explaining away every single one of many flags is visible as its own data point.
    const totalFlagged = analysis.flagged_discrepancies.length;
    const totalExplained = discrepancyExplanations.length;
    const discrepancyResolutionPattern =
      totalFlagged > 0 ? Math.round((totalExplained / totalFlagged) * 100) / 100 : null;

    // ── Compute commitment score ──────────────────────────────────────────
    const commitmentScore =
      Math.round(
        (githubScore * githubWeight + interviewScore * interviewWeight) * 100,
      ) / 100;

    // ── Generate score explanation summary ─────────────────────────────────
    let scoreExplanationSummary: string | null = null;
    try {
      scoreExplanationSummary = await this.generateScoreExplanation(
        commitmentScore,
        githubScore,
        interviewScore,
        githubWeight,
        interviewWeight,
        githubConfidence,
      );
    } catch (err) {
      this.logger.warn(`Score explanation generation failed: ${(err as Error).message}`);
      // Non-fatal — continue without explanation
    }

    // ── Persist bio_summary to interview session ──────────────────────────
    const bioSummary = analysis.bio_summary || null;

    // ── Persist structured output + update session status ─────────────────
    await this.prisma.interviewSession.update({
      where: { id: sessionId },
      data: {
        status: 'complete',
        structuredOutput: analysis as any,
        bioSummary,
      },
    });

    // ── Write commitment_scores row ───────────────────────────────────────
    const discrepancies = analysis.flagged_discrepancies.map((d) => ({
      repo: d.repo,
      issue: d.issue,
      userExplanation: d.user_explanation,
    }));

    await this.prisma.commitmentScore.upsert({
      where: { userId },
      create: {
        userId,
        githubScore,
        interviewScore,
        commitmentScore,
        appliedGithubWeight: githubWeight,
        appliedInterviewWeight: interviewWeight,
        declaredHoursPerDay: analysis.declared_hours_per_day,
        flaggedDiscrepancies: discrepancies as any,
        cappedDiscrepancyAdjustments: cappedAdjustments as any,
        discrepancyResolutionPattern,
        communicationNotes: analysis.communication_style_notes,
        scoreExplanationSummary,
      },
      update: {
        githubScore,
        interviewScore,
        commitmentScore,
        appliedGithubWeight: githubWeight,
        appliedInterviewWeight: interviewWeight,
        declaredHoursPerDay: analysis.declared_hours_per_day,
        flaggedDiscrepancies: discrepancies as any,
        cappedDiscrepancyAdjustments: cappedAdjustments as any,
        discrepancyResolutionPattern,
        communicationNotes: analysis.communication_style_notes,
        scoreExplanationSummary,
      },
    });

    // ── Also update the denormalised commitmentScore, roleTags, and primaryStack on User ─────────────
    const userUpdateData: Record<string, unknown> = { commitmentScore };
    if (Array.isArray(analysis.role_tags) && analysis.role_tags.length > 0) {
      userUpdateData.roleTags = analysis.role_tags;
    }
    if (analysis.primary_stack) {
      userUpdateData.primaryStack = analysis.primary_stack;
    }

    await this.prisma.user.update({
      where: { id: userId },
      data: userUpdateData,
    });

    this.logger.log(
      `Interview complete for user ${userId} — commitmentScore: ${commitmentScore} ` +
      `(github: ${githubScore} × ${githubWeight} + interview: ${interviewScore} × ${interviewWeight}) ` +
      `[confidence: ${githubConfidence}]`,
    );

    // ── Emit final event to frontend ──────────────────────────────────────
    emitComplete({
      commitmentScore,
      githubScore,
      interviewScore,
      appliedGithubWeight: githubWeight,
      appliedInterviewWeight: interviewWeight,
      declaredHoursPerDay: analysis.declared_hours_per_day,
      flaggedDiscrepancies: discrepancies,
      communicationStyleNotes: analysis.communication_style_notes,
      discrepancyResolutionPattern,
      scoreExplanationSummary,
      githubConfidence,
      preInterviewWarning: WARNING_TEXTS.preInterview,
    });
  }

  // ── Private: get the question set based on confidence tier ────────────────

  /**
   * Returns the full ordered list of questions to ask based on github_confidence.
   *
   * - High confidence: baseline questions only (+ targeted Gemini follow-ups)
   * - Low confidence (new account): baseline + expanded compensatory questions
   * - Low confidence (old account): baseline + expanded + old-account question
   * - Insufficient: same as low-confidence-old-account path
   */
  private getQuestionSet(
    githubConfidence: GithubConfidenceTier,
    accountCreatedAt: Date | null,
  ): string[] {
    if (githubConfidence === 'high') {
      return [...BASELINE_QUESTIONS];
    }

    // Low or insufficient — include expanded questions
    const questions = [...BASELINE_QUESTIONS, ...LOW_CONFIDENCE_EXPANDED_QUESTIONS];

    // Determine if this is an old account (>1 year) with thin data
    const isOldAccount = accountCreatedAt
      ? (Date.now() - new Date(accountCreatedAt).getTime()) > ACCOUNT_AGE_THRESHOLD_DAYS * 24 * 60 * 60 * 1000
      : false;

    if (isOldAccount || githubConfidence === 'insufficient') {
      const formattedDate = accountCreatedAt
        ? new Date(accountCreatedAt).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
        : 'some time ago';
      questions.push(
        OLD_ACCOUNT_QUESTION_TEMPLATE.replace('{accountCreatedDate}', formattedDate),
      );
    }

    return questions;
  }

  // ── Private: stream a single Gemini turn ─────────────────────────────────

  /**
   * Streams one Gemini response turn.
   * - If `injectedQuestion` is provided, it sends that as the AI message (for baseline questions)
   *   and appends it to transcript without calling Gemini.
   * - Otherwise, sends the full transcript as context and asks Gemini for the next message.
   *
   * Returns the full assembled text of the AI's response.
   */
  private async streamGeminiTurn(
    sessionId: string,
    userId: string,
    systemPrompt: string,
    currentTranscript: TranscriptEntry[],
    injectedQuestion: string | null,
    onChunk: (chunk: string) => void,
    onComplete: (fullText: string, turnIndex: number, isFinished?: boolean) => void,
    turnIndex: number,
  ): Promise<string> {
    // ── Baseline injected question path ────────────────────────────────────
    if (injectedQuestion) {
      await this.appendToTranscript(sessionId, 'assistant', injectedQuestion);
      onChunk(injectedQuestion);
      onComplete(injectedQuestion, turnIndex, false);
      return injectedQuestion;
    }

    // ── Gemini streaming path ──────────────────────────────────────────────
    const model = this.genAI.getGenerativeModel({
      model: GEMINI_MODEL,
      systemInstruction: systemPrompt,
      safetySettings: SAFETY_SETTINGS,
    });

    // Gemini history MUST start with role 'user' and alternate.
    const rawHistory = currentTranscript.map((entry) => ({
      role: entry.role === 'assistant' ? ('model' as const) : ('user' as const),
      parts: [{ text: entry.content }],
    }));

    const history =
      rawHistory.length > 0 && rawHistory[0].role === 'model'
        ? [
            {
              role: 'user' as const,
              parts: [{ text: 'Hello, I am ready for the interview.' }],
            },
            ...rawHistory,
          ]
        : rawHistory;

    const chat = model.startChat({ history });

    const userMessage =
      'Continue the interview. Ask your next follow-up question based on the candidate responses so far. If you have gathered sufficient information across all areas (projects, completion, difficulty handling, communication, time commitment) and probed any GitHub discrepancies, respond with exactly [INTERVIEW_COMPLETE] followed by a brief closing statement.';

    let rawFullText = '';

    try {
      const result = await chat.sendMessageStream(userMessage);

      for await (const chunk of result.stream) {
        const candidate = chunk.candidates?.[0];
        if (candidate?.finishReason === 'SAFETY') {
          this.logger.warn(`[SAFETY_TRIGGERED] session=${sessionId}, turn=${turnIndex}, reason=finishReason:SAFETY`);
          const safetyFallback = "Let's keep this focused on the project — could you rephrase that?";
          await this.appendToTranscript(sessionId, 'assistant', safetyFallback);
          onChunk(safetyFallback);
          onComplete(safetyFallback, turnIndex, false);
          return safetyFallback;
        }

        const chunkText = chunk.text();
        if (chunkText) {
          rawFullText += chunkText;
          // Strip [INTERVIEW_COMPLETE] from chunk before streaming to client
          const cleanedChunk = chunkText.replace(/\[INTERVIEW_COMPLETE\]/g, '');
          if (cleanedChunk) {
            onChunk(cleanedChunk);
          }
        }
      }
    } catch (err) {
      const errorMsg = (err as Error).message || '';
      if (errorMsg.includes('SAFETY') || errorMsg.includes('blocked') || errorMsg.includes('candidate')) {
        this.logger.warn(`[SAFETY_TRIGGERED] session=${sessionId}, turn=${turnIndex}, reason=${errorMsg}`);
        const safetyFallback = "Let's keep this focused on the project — could you rephrase that?";
        await this.appendToTranscript(sessionId, 'assistant', safetyFallback);
        onChunk(safetyFallback);
        onComplete(safetyFallback, turnIndex, false);
        return safetyFallback;
      }
      throw new Error(`Gemini streaming failed: ${errorMsg}`);
    }

    const isFinished = rawFullText.includes('[INTERVIEW_COMPLETE]');
    let cleanText = rawFullText.replace(/\[INTERVIEW_COMPLETE\]/g, '').trim();
    if (!cleanText && isFinished) {
      cleanText = "Thank you for sharing your experience! That completes all our questions.";
    }

    await this.appendToTranscript(sessionId, 'assistant', cleanText);
    onComplete(cleanText, turnIndex, isFinished);
    return cleanText;
  }

  // ── Private: structured analysis via Gemini responseSchema ───────────────

  private async runStructuredAnalysis(
    transcript: TranscriptEntry[],
  ): Promise<InterviewAnalysis> {
    const model = this.genAI.getGenerativeModel({
      model: GEMINI_MODEL,
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: ANALYSIS_RESPONSE_SCHEMA,
      },
      safetySettings: SAFETY_SETTINGS,
    });

    const transcriptText = transcript
      .map((t) => `${t.role === 'assistant' ? 'Interviewer' : 'Candidate'}: ${t.content}`)
      .join('\n\n');

    const prompt = `
You are analysing a commitment interview transcript. Based on the conversation below, produce a structured assessment.

TRANSCRIPT:
${transcriptText}

Produce the JSON output now. Be objective and neutral — flag discrepancies as data points, not accusations.
Specificity score should reflect how concrete and specific the candidate's answers were (vague = low, detailed and verifiable = high).
For flagged_discrepancies, only include items where there is a genuine tension between what was said and what the GitHub data shows.
If no discrepancies exist, return an empty array.
For bio_summary, extract a concise summary from the candidate's response to "Tell us about yourself" — their background, interests, and what excites them.
For discrepancy_explanations, assess each flagged discrepancy where the user provided an explanation:
  - original_weight: how much this discrepancy would normally weigh (0-1)
  - explanation_quality: how concrete and verifiable the explanation was (0-1)
  - reduction_applied: the actual reduction, capped at ${MAX_DISCREPANCY_REDUCTION} (i.e., max 50% reduction — an explanation can never fully erase a discrepancy)
If there are no discrepancies or no explanations, return an empty array for discrepancy_explanations.
    `.trim();

    const result = await model.generateContent(prompt);
    const raw = result.response.text();

    let parsed: InterviewAnalysis;
    try {
      parsed = JSON.parse(raw) as InterviewAnalysis;
    } catch {
      throw new Error(`Gemini returned non-JSON output: ${raw.slice(0, 200)}`);
    }

    // Basic schema validation
    if (
      typeof parsed.specificity_score !== 'number' ||
      typeof parsed.declared_hours_per_day !== 'number' ||
      !Array.isArray(parsed.flagged_discrepancies) ||
      typeof parsed.communication_style_notes !== 'string' ||
      typeof parsed.bio_summary !== 'string'
    ) {
      throw new Error('Gemini structured output did not match expected schema');
    }

    // Ensure discrepancy_explanations exists (default to empty if missing)
    if (!Array.isArray(parsed.discrepancy_explanations)) {
      parsed.discrepancy_explanations = [];
    }

    return parsed;
  }

  // ── Private: generate score explanation summary ──────────────────────────

  /**
   * Generates a short, natural-language paragraph explaining the score's
   * composition in plain terms. Uses Gemini structured output.
   */
  private async generateScoreExplanation(
    commitmentScore: number,
    githubScore: number,
    interviewScore: number,
    githubWeight: number,
    interviewWeight: number,
    githubConfidence: GithubConfidenceTier,
  ): Promise<string> {
    const model = this.genAI.getGenerativeModel({
      model: GEMINI_MODEL,
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: SCORE_EXPLANATION_SCHEMA,
      },
      safetySettings: SAFETY_SETTINGS,
    });

    const confidenceContext =
      githubConfidence === 'high'
        ? 'The user has strong GitHub history, so GitHub activity was weighted heavily (70%).'
        : githubConfidence === 'low'
          ? 'The user has limited GitHub history, so interview responses were given more weight (65%) to compensate for sparse GitHub evidence.'
          : 'The user has no qualifying GitHub repositories, so the score is based entirely on interview responses.';

    const prompt = `
Generate one short, natural-language paragraph explaining this commitment score in plain terms.

Score: ${commitmentScore}/100
GitHub Score: ${githubScore}/100 (weighted at ${(githubWeight * 100).toFixed(0)}%)
Interview Score: ${interviewScore}/100 (weighted at ${(interviewWeight * 100).toFixed(0)}%)
GitHub Confidence: ${githubConfidence}
${confidenceContext}

The explanation should:
- Reference whether GitHub or interview was weighted more heavily and why
- Be warm and encouraging, not clinical
- Close with something like: "This is a starting signal — it becomes more accurate once you've completed a project and received peer ratings."
- Be 7-10 sentences maximum
    `.trim();

    const result = await model.generateContent(prompt);
    const raw = result.response.text();
    const parsed = JSON.parse(raw) as { explanation: string };
    return parsed.explanation;
  }

  // ── Private: system prompt builder ───────────────────────────────────────

  /**
   * Builds the system prompt for Gemini, now with branching based on
   * github_confidence tier to provide appropriate context and instructions.
   */
  private buildSystemPrompt(
    repos: RepoSignals[],
    githubConfidence: GithubConfidenceTier,
    accountCreatedAt: Date | null,
  ): string {
    const repoSummary = repos
      .map(
        (r) =>
          `  - ${r.name} (${r.isCollaborative ? 'collaborative' : 'solo'}): commit consistency ${(r.commitGapConsistency * 100).toFixed(0)}%, ` +
          `PR merge rate ${r.prMergeRatio !== null ? (r.prMergeRatio * 100).toFixed(0) + '%' : 'N/A (0 PRs)'}, ` +
          `issue close rate ${r.issueCloseRatio !== null ? (r.issueCloseRatio * 100).toFixed(0) + '%' : 'N/A (0 issues)'}, ` +
          `completion signal ${(r.completionSignal * 100).toFixed(0)}%, ` +
          `repo score ${r.repoScore}/100`,
      )
      .join('\n');

    let confidenceContext: string;
    if (githubConfidence === 'high') {
      confidenceContext = `
CONFIDENCE LEVEL: HIGH
The user has sufficient GitHub history to trust the data at face value. Use repo-specific follow-ups.`;
    } else if (githubConfidence === 'low') {
      const accountAge = accountCreatedAt
        ? Math.floor((Date.now() - new Date(accountCreatedAt).getTime()) / (1000 * 60 * 60 * 24 * 365))
        : null;
      const isNewAccount = accountAge !== null && accountAge < 1;

      if (isNewAccount) {
        confidenceContext = `
CONFIDENCE LEVEL: LOW (New Developer)
This user has a relatively new GitHub account with limited history. This is NOT a red flag — they may be
genuinely new to public development. Ask broader questions about their experience, including non-GitHub projects.
Focus on specificity and consistency in their answers to compensate for sparse GitHub signals.`;
      } else {
        confidenceContext = `
CONFIDENCE LEVEL: LOW (Established Account, Thin Data)
This user has had a GitHub account for over a year but has limited public activity. This is worth exploring
neutrally — there could be many legitimate reasons (work on other platforms, career transition).
Ask the account-age context question naturally and assess their explanation. Do NOT assume dishonesty.`;
      }
    } else {
      confidenceContext = `
CONFIDENCE LEVEL: INSUFFICIENT
No qualifying repositories were found. The interview is the primary signal for this user's commitment level.
Ask more probing questions about their development experience, project history, and work habits.
Be thorough but fair — weight specificity and consistency in their answers heavily.`;
    }

    return `
You are TruMatch's commitment interviewer. Your role is neutral fact-gathering and consistency-checking — NOT judgment.

RULES:
- Ask one question at a time. Never ask multiple questions in a single turn.
- Be conversational and warm, not clinical or interrogative.
- Never accuse the user of lying. If something doesn't add up, flag it as a data point: "I noticed X in your GitHub data — can you tell me more about that?"
- Ground any follow-up questions in the ACTUAL GitHub data below. Do not invent data or ask generic questions unrelated to the user's real repos.
- Reference repos by their actual names when asking follow-up questions.
- When you have covered all baseline areas and any significant discrepancies, emit [INTERVIEW_COMPLETE] to signal the interview is done.
- For low-confidence users, ask one light, conversational technical-reasoning question scoped to their claimed stack (not a formal coding test).
- For users with an immediate specific follow-up opportunity (they named a project), ask about the language/framework used and the actual blocker that took longest to solve.
- IMPORTANT: GitHub sync scans BOTH public AND private repositories (via GitHub OAuth repo scope). Do NOT accept "my work is in private repos" or "I work in private repositories" as a sufficient resolving explanation on its own. If the candidate offers this, remind them neutrally that private repos were already included in the scan, and ask a direct, specific follow-up (e.g. what specific projects or tech stacks they worked on, or if their work was under a different GitHub account or enterprise organization).

${confidenceContext}

GITHUB DATA FOR THIS USER:
${repoSummary.length > 0 ? repoSummary : '  (No qualifying repositories found)'}

WHAT TO PROBE:
- Projects worked on (match against actual repo names if available)
- Projects finished vs abandoned (compare against completion signals and commit drop-offs)
- How they handle difficulty (look for repos with low completion signal)
- Communication with teammates (no direct GitHub metric, ask openly)
- Hours per day available (declared_hours_per_day — capture this precisely)
- Any repos with very low PR merge rate or issue close rate — ask why without assuming the worst
${githubConfidence !== 'high' ? '- Development experience beyond GitHub (other platforms, private work, learning path)\n- Specific technical depth in their claimed stack' : ''}
    `.trim();
  }

  // ── Private: append a single entry to a session's transcript ─────────────

  private async appendToTranscript(
    sessionId: string,
    role: 'assistant' | 'user',
    content: string,
  ): Promise<void> {
    const session = await this.prisma.interviewSession.findUnique({
      where: { id: sessionId },
      select: { transcriptJson: true },
    });

    const existing = (session?.transcriptJson as unknown as TranscriptEntry[]) ?? [];
    const updated: TranscriptEntry[] = [
      ...existing,
      { role, content, timestamp: new Date().toISOString() },
    ];

    await this.prisma.interviewSession.update({
      where: { id: sessionId },
      data: { transcriptJson: updated as any },
    });
  }
}
